default_language_version:
  python: python3.10
exclude: ".git|.tox"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        types: [python]

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.2
    hooks:
    -   id: pycln

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        types: [python]

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        types: [file]
        types_or: [javascript, jsx, ts, tsx, vue]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.27.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.3.0
          - eslint-config-prettier@8.3.0
          - eslint-plugin-vue@8.4.0
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - eslint-plugin-prettier@4.2.1
        types: [file]
        types_or: [javascript, jsx, ts, tsx, vue]
        exclude: ^front\/cypress/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: detect-private-key

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: Detect secrets
        description: Detects high entropy strings that are likely to be passwords.
        entry: detect-secrets-hook
        language: python
        # for backward compatibility
        files: .*
